### ISSUE TITLE
Main ToDo list before vob

### ISSUE THREAD

**Issue by uvinduperera** [fosslk/Volunteer-onboarding-Process#5]
- [ ] User Group for mentors

- [ ] email thread (Incase)

- [ ] kanban board touch-ups
  - [ ]  4 cards for each week

- [ ] Final introduction about, projects to be given
